spring:
  profiles:
    default: local

  application:
    name: apigateway-service

  output:
    ansi:
      enabled: always

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh, info, metrics, prometheus
