server:
  port: 8084

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:~/justShopApplication
    username: sa
    password:

  cloud:
    config:
      enabled: false

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 500
    defer-datasource-initialization: true

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

token:
  expiration_time: 86400000
  secret: springboot_my_json_web_token_dev

kafka:
  bootstrap:
    server:
      config: 127.0.0.1:9092