spring:
  config:
    import: optional:configserver:http://config-service:8888
    active:
      on-profile: prod

  cloud:
    config:
      name: point-service
    refresh:
      extra-refreshable: com.zaxxer.hikari.HikariDataSource