server:
  port: 0

spring:
  profiles:
    default: dev

  application:
    name: coupon-service

  output:
    ansi:
      enabled: always

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:~/justShopApplication
    username: sa
    password:

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh, info, metrics, prometheus
