spring:
  config:
    import: optional:configserver:http://config-service:8888
    activate:
      on-profile: prod
  cloud:
    config:
      name: member-service
    refresh:
      extra-refreshable: com.zaxxer.hikari.HikariDataSource