server:
  port: 8083

spring:
  output:
    ansi:
      enabled: always

  config:
    activate:
      on-profile: test

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:~/justShopApplication
    username: sa
    password:

  cloud:
    config:
      enabled: false

  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 500

  sql:
    init:
      mode: never

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka

kafka:
  bootstrap:
    server:
      config: 127.0.0.1:9092