server:
  port: 8083

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3305/justshop_local
    username: root
    password: 1234

  cloud:
    config:
      enabled: false
    refresh:
      extra-refreshable: com.zaxxer.hikari.HikariDataSource

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 500
    defer-datasource-initialization: true

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

token:
  expiration_time: 86400000
  secret: springboot_my_json_web_token_dev

kafka:
  bootstrap:
    server:
      config: 127.0.0.1:9092