server:
  port: 8082

spring:
  jackson:
    property-naming-strategy: SNAKE_CASE

  output:
    ansi:
      enabled: always

  datasource:
    url: jdbc:h2:mem:~/justShopApplication
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    # (2.5~) Hibernate 초기화 이후 data.sql 실행, 테스트 데이터 넣을 때 넣는 옵션
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true  # 추가

token:
  expiration_time: 86400000
  secret: springboot_my_json_web_token_default