server:
  port: 8087

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:~/justShopApplication
    username: sa
    password:

  cloud:
    config:
      enabled: false

  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
#        default_batch_fetch_size: 500

  sql:
    init:
      mode: never

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

kafka:
  bootstrap:
    server:
      config: 127.0.0.1:9092
