spring:
  output:
    ansi:
      enabled: always
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:~/justShopApplication
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 1000
  sql:
    init:
      mode: never